# Generated by Django 3.0.8 on 2021-11-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('operation_start', models.TimeField()),
                ('operation_end', models.TimeField()),
            ],
        ),
    ]
