# Generated by Django 3.0.8 on 2021-11-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicuser',
            name='address',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicuser',
            name='sex',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
