# Generated by Django 3.0.8 on 2021-12-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20211212_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicuser',
            name='offense_count',
            field=models.IntegerField(null=True),
        ),
    ]
