# Generated by Django 3.0.8 on 2021-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20211121_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicuser',
            name='middle_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
