# Generated by Django 3.0.8 on 2021-11-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinicuser_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicuser',
            name='contact',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
