# Generated by Django 3.0.8 on 2021-11-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_appointment_category_inquiry_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='end_day',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='starting_day',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
