# Generated by Django 3.0.8 on 2021-11-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20211117_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='end_day',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='starting_day',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
