# Generated by Django 3.0.8 on 2021-11-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20211121_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
