# Generated by Django 3.0.8 on 2021-11-19 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_role', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='job', to='clinic.Role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.ManyToManyField(null=True, to='clinic.Expertise'),
        ),
    ]
