# Generated by Django 3.0.8 on 2021-11-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20211120_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='clinic.Expertise'),
        ),
    ]
