# Generated by Django 3.0.8 on 2021-11-23 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_auto_20211121_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReceived', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=120)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifRecipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
