# Generated by Django 3.0.8 on 2021-11-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
