# Generated by Django 3.0.8 on 2021-12-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_auto_20211123_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicuser',
            name='offenseCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicuser',
            name='user_category',
            field=models.CharField(default='Patient', max_length=10),
            preserve_default=False,
        ),
    ]
