# Generated by Django 3.0.8 on 2021-12-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20211202_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicuser',
            old_name='offenseCount',
            new_name='offense_count',
        ),
    ]
