# Generated by Django 3.0.8 on 2021-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_auto_20211202_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='assigned_clinic',
        ),
        migrations.AddField(
            model_name='staff',
            name='assigned_clinic',
            field=models.ManyToManyField(related_name='assigned_clinic', to='clinic.Clinic'),
        ),
    ]
